config/routes.rb
Rails.application.routes.draw do
  resources :gestion_usuario do
    get :crear_cuentas, :on => :collection
    get :restablecer_cuentas, :on =>:collection
  end
   



  resources :solicitudes_fichas do
    post :readpdf, :on => :collection
    get :readpdf, :on => :collection
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  get 'anuncios/index'
  get "/anuncios", to: "anuncios#index"

  get "anuncios", to:"anuncios#index"
  get "anuncios/new", to: "anuncios#new"
  get "anuncios/:id", to:"anuncios#show"
  get "anuncios/:id/edit", to:"anuncios#edit"
  patch "/anuncios/:id", to:"anuncios#update", as: :anuncio
  post "anuncios", to:"anuncios#create"
  delete "/anuncios/:id", to:"anuncios#destroy"


  match 'solicitudes_fichas/aspi', :controller => 'solicitudes_fichas', :action => 'aspi', via: :get

  resources :solicitud_propedeutico do
    get :search_data_aspirantes_request, :on => :collection
    get :search_data_tipo_request, :on => :collection
    get :search_monto_request, :on => :collection
    get :search_concepto_request, :on => :collection
    post :guardar_sol, :on => :collection
  end

  resources :solicitudes_inscripciones do
    get :new_aspirante, :on => :collection
  end

  resources :solicitudes_reinscripciones

  resources :aspirantes do
    # get :show, :on => :collection
    post :towns_options, :on => :collection
    post :localities_options, :on => :collection

    post :towns_options_edit, :on => :collection
    post :localities_options_edit, :on => :collection

    post :towns_options_father, :on => :collection
    post :localities_options_father, :on => :collection
    post :towns_options_father_edit, :on => :collection
    post :localities_options_father_edit, :on => :collection


    post :towns_options_mother, :on => :collection
    post :localities_options_mother, :on => :collection

    post :towns_options_mother_edit, :on => :collection
    post :localities_options_mother_edit, :on => :collection


    post :towns_options_tutor, :on => :collection
    post :localities_options_tutor, :on => :collection

    post :towns_options_tutor_edit, :on => :collection
    post :localities_options_tutor_edit, :on => :collection

    get :autocomplete_origin_school, :on => :collection
    get :edit, :on => :collection
    get :new_documento, :on => :collection
    get :edit_documento, :on => :collection
    post :save_documentos, :on => :collection
    post :save_edit_documentos, :on => :collection
    get :registered_nss, :on => :collection
    get :registered_escuela, :on => :collection
  end
  resources :escolares

  resources :fichas do
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  devise_for :usuarios,controllers: { registrations: 'registrations' },  path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new_account', edit: 'edit/profile' }

  root 'home#index'
end

app/models/aspirante.rb
class Aspirante < ActiveRecord::Base
  HOMBRE = 'H'
  MUJER = 'M'
  SOLICITUD = 'SOLICITUD'
  NUEVO_DOCUMENTO = 'NUEVO_DOCUMENTO'

  has_one :dato_personal, :dependent => :destroy
  has_one :antecedente_academico, :dependent => :destroy

  has_many :aspirante_familiares
  has_many :documentaciones_entregadas
  has_many :documentos, through: :documentaciones_entregadas
  has_many :familiares, through: :aspirante_familiares
  has_many :fichas
  has_many :inscripciones_propedeuticos
  has_many :preregistros_pagos
  has_many :solicitudes_fichas
  has_many :solicitudes_propedeuticos

  belongs_to :usuario

  accepts_nested_attributes_for :dato_personal
  accepts_nested_attributes_for :antecedente_academico

  def full_name
    self.get_apellido_paterno + self.get_apellido_materno + self.nombre.to_s
  end

  def get_apellido_paterno
    self.apellido_paterno.blank? ? '' : self.apellido_paterno.to_s.strip + ' '
  end

  def get_apellido_materno
    self.apellido_materno.blank? ? '' : self.apellido_materno.to_s.strip + ' '
  end

  def tiene_ficha?
    tiene = ""
    periodo_propedeutico = PeriodoFicha.where("actual = ?", true).first
    if !periodo_propedeutico.id.blank?
      ficha = SolicitudFicha.joins(:ficha, :sede_ficha => :periodo_ficha).
          where("fichas.ciclo_id = ? AND fichas.aspirante_id = ? AND periodos_fichas.tipo = ?", periodo_propedeutico.ciclo_id, self.id, periodo_propedeutico.tipo).first
      unless ficha.blank?
        tiene = ficha.ficha.estado unless ficha.ficha.blank?
      else
        tiene = "NINGUNO"
      end
    end
    tiene
  end

  def tiene_prope?
    tiene = ""
    periodo_propedeutico = PeriodoPropedeutico.where("actual = ?", true).first

    if !periodo_propedeutico.id.blank?
      prope = InscripcionPropedeutico.joins(:solicitud_propedeutico => :periodo_propedeutico).
          where("solicitudes_propedeuticos.aspirante_id = ? AND periodos_propedeuticos.ciclo_id = ? AND periodos_propedeuticos.tipo = ? ", self.id, periodo_propedeutico.ciclo_id, periodo_propedeutico.tipo).first
      unless prope.blank?
        tiene= prope.estado
      else
        tiene= "NINGUNO"
      end
    end
    tiene
  end

  #Este método me permite saber si un aspirante, ya ha realizado o no alguna solicitud en el periodo en el que se encuentra actualmente el periodo de fichas
  def is_aspirante_with_request?
    tiene = ""

    periodos_fichas = PeriodoFicha.where("actual = ?", true)
    ciclo_periodo = periodos_fichas[0]
    solicitud_ficha_ciclo_actual = SolicitudFicha.joins('INNER JOIN aspirantes ON solicitudes_fichas.aspirante_id = aspirantes.id').where(:aspirantes => {:curp => self.curp.upcase},:solicitudes_fichas => {:ciclo_id => ciclo_periodo.ciclo_id}) unless ciclo_periodo.blank?

    # Caso if: el aspirante cuenta con una solicitud en el ciclo actual
    # Caso else: el aspirante no cuenta con una solicitud en el ciclo actual
    if !solicitud_ficha_ciclo_actual.blank?
      documentos = DocumentoFicha.has_documentos_fichas(self.id)
      if !documentos.blank?
        tiene = SOLICITUD
      else
        tiene = NUEVO_DOCUMENTO
      end
    else
      tiene = NUEVO_DOCUMENTO
    end
    return tiene
  end

  def validacion_calf_aspi?
    periodos_fichas = PeriodoPropedeutico.where("actual = ?", true).first
    @propecalifi = CalificacionPropedeutico.joins(:inscripcion_propedeutico => [:aspirante, :solicitud_propedeutico=>:periodo_propedeutico]).
        where("inscripciones_propedeuticos.aspirante_id = ? AND solicitudes_propedeuticos.periodo_propedeutico_id =?",  self.id,periodos_fichas.id).first

  end

  #Este metodo busca el periodo activo en el portal de NES, busca los periodos de prope pertenecientes al ciclo marcado como actual
  # busca si el estado del aspirtante es ACEPTADO O ACEPTADO CONDICIONADO, para despues filtrar el estado del prope
  # En la vista _sidebar se manda a llamar el def tiene_prope_q y se hace la comparacion para que visualice la opcion de solicitud inscripcion.
  def tiene_prope_q?
    tiene = "NINGUNO"
    ciclo=Ciclo.get_ciclo_actual
    periodos_propedeuticos = PeriodoPropedeutico.where("ciclo_id = ?",ciclo.id )
    if !periodos_propedeuticos.blank?
    periodos_propedeuticos.each do |pp|

     prope = InscripcionPropedeutico.joins(:calificaciones_propedeuticos, :solicitud_propedeutico => :periodo_propedeutico).
          where("solicitudes_propedeuticos.aspirante_id = ? AND periodos_propedeuticos.id = ?", self.id, pp.id).first
     if !prope.blank?
       if prope.estado.eql?("ACEPTADO") or prope.estado.eql?("ACEPTADO CONDICIONADO")
       if !prope.calificaciones_propedeuticos.blank?
         tiene= prope.estado
         break
       end
       end
       end
      end
    end
    tiene
  end
end

app/controllers/aspirantes_controller.rb
class AspirantesController < ApplicationController
  before_action :require_user
  require 'piet'
  def index; end
  def new
    @anuncio=Anuncio.all

    @aspirante = Aspirante.new
    @aspirante.build_dato_personal
    @aspirante.build_antecedente_academico
    @lenguas_indigenas = LenguaIndigena.order(:nombre).all
    @paises = Lugar.where("tipo = ?", Lugar::PAIS)
    @pais  = Lugar.get_mexico
    @estados = Lugar.where("tipo = 'ESTADO' AND lugar_id = ?", @pais.id)
    @parent= Parentesco.all
    @escuela_proc = EscuelaProcedente.all


  end
  def show
    @aspirante= Aspirante.find(params[:id])
  end


  def edit
    @accion ='edit'
    @aspirante = Aspirante.find(params[:id])
    @aspirante.dato_personal
    @aspirante.antecedente_academico
    @lugar=DatoPersonal.find_by_aspirante_id params[@aspirante.id]
    #@fam=AspiranteFamiliar.find_by_aspirante_id @aspirante.id
    #@padre = []
    #padre=Familiar.find (@fam.familiar_id).padre.where(:parentesco=>'MADRE')
    ma=@aspirante.familiares.where(:parentesco=>'MADRE').first
    @datamed=DatoPersonal.find_by_aspirante_id params[@aspirante.id]
    @dataaca=AntecedenteAcademico.find_by params[@aspirante.id]
    @aspirante.dato_personal.direccion
    @aspirante_estado_civil=@aspirante.dato_personal.estado_civil.first

    # @aspirante.dato_personal.lenguas_indigenas.each do |n|
    #   puts "direccions"+      n.nombre.to_s
    # end

    # obtiene el estado del aspirante
    @aspirante_localidad_id = @aspirante.dato_personal.direccion.lugar.id
    municipio_aux = Lugar.where(:id => @aspirante.dato_personal.direccion.lugar.lugar_id).first
    @aspirante_municipio_id = municipio_aux.id
    estado_aux = Lugar.where(:id => municipio_aux.lugar_id).first
    @aspirante_estado_id = estado_aux.id


    # obtiene el estado del padre del aspirante
    padre=@aspirante.familiares.where(:parentesco=>'PADRE').last
    @padre_localidad_id = padre.direccion.lugar.id
    municipio_aux = Lugar.where(:id => padre.direccion.lugar.lugar_id).first
    @padre_municipio_id = municipio_aux.id unless municipio_aux.blank?
    estado_aux = Lugar.where(:id => municipio_aux.lugar_id).first unless municipio_aux.blank?
    @padre_estado_id = estado_aux.id

    # obtiene el estado de la madre del aspirante
    madre=@aspirante.familiares.where(:parentesco=>'MADRE').last
    @madre_localidad_id = madre.direccion.lugar.id
    municipio_aux = Lugar.where(:id => madre.direccion.lugar.lugar_id).first
    @madre_municipio_id = municipio_aux.id unless municipio_aux.blank?
    estado_aux = Lugar.where(:id => municipio_aux.lugar_id).first unless municipio_aux.blank?
    @madre_estado_id = estado_aux.id
    # obtiene el estado de la madre del aspirante
    tu=@aspirante.familiares.where(:tutor=>'TRUE').last
    @tutor_localidad_id = tu.direccion.lugar.id
    municipio_aux = Lugar.where(:id => tu.direccion.lugar.lugar_id).first
    @tutor_municipio_id = municipio_aux.id unless municipio_aux.blank?
    estado_aux = Lugar.where(:id => municipio_aux.lugar_id).first unless municipio_aux.blank?
    @tutor_estado_id = estado_aux.id

    @dataaca=@aspirante.antecedente_academico
    @lenguas_indigenas = LenguaIndigena.order(:nombre)
    @paises = Lugar.where("tipo = ?", Lugar::PAIS)
    @pais  = Lugar.get_mexico
    @estados = Lugar.where("tipo = 'ESTADO' AND lugar_id = ?", @pais.id)
  end

  def aspi_params
    params.require(:aspirante).permit(:nombre, :apellido_paterno, :apellido_materno, :sexo)
  end
  def datoper_params
    params.require(:dato_personal).permit(:lugar_nacimiento, :telefono, :nss, :nacionalidad, :email, :estado_civil)
  end

  def update
    @accion ='edit'
    @aspirante = Aspirante.find(params[:id])
    @dataaca=@aspirante.antecedente_academico
    # puts "dsfffff"+@dataaca.area_conocimiento_id.to_s

    if @aspirante.update(aspirante_params)
      dato_medico = save_medical_data(params[:dato_medico])
      @aspirante.dato_personal.dato_medico_id = dato_medico.id
      pais = Lugar.find(params[:direccion][:pais])
      if pais.nombre == 'MÉXICO'
        if params[:direccion][:localidad].nil?
          lugar=Lugar.find '300598'
        else
          lugar = Lugar.find(params[:direccion][:localidad])
        end
        data_direccion=save_direccion_data(params[:direccion])
        @aspirante.dato_personal.direccion_id=data_direccion.id
        dp = @aspirante.dato_personal.id
        dato_personal  = DatoPersonal.find(dp)

        lenguas = params[:datos_lenguas][:lengua_indigena]
        lenguas.each do |lenguas|
          DatoPersonalLenguaIndigena.new(dato_personal_id: dato_personal.id, lengua_indigena_id: lenguas).save
        end
      end
      # puts "params familiar: " + params[:familiar].to_s
      # puts "padre nombre: " + params[:familiar][:nombre_padre]
      padre = save_father(params[:familiar])
      AspiranteFamiliar.new(aspirante_id: @aspirante.id, familiar_id: padre.id).save
      madre = save_mother(params[:familiar])
      AspiranteFamiliar.new(aspirante_id: @aspirante.id, familiar_id: madre.id).save
      if Parentesco.find(params[:parentesco_tutor]).parentesco == Familiar::PADRE || Parentesco.find(params[:parentesco_tutor]).parentesco == Familiar::MADRE

      else
        @tutor = save_tutor(params[:familiar])
        AspiranteFamiliar.new(aspirante_id: @aspirante.id, familiar_id: @tutor.id).save
      end
      escuela = EscuelaProcedente.find_by_nombre(params[:dato_academico][:escuela_procedente_nombre])
      # antecedente_academico = AntecedenteAcademico.new(escuela_procedente_id: escuela.id, aspirante_id: @aspirante.id, fecha_inicio: params[:dato_academico][:fecha_inicio], fecha_fin: params[:dato_academico][:fecha_fin], promedio: params[:dato_academico][:promedio], especialidad: params[:dato_academico][:especialidad], area_conocimiento_id: params[:dato_academico][:area_conocimiento_id], año_inicio: params[:dato_academico][:año_inicio], año_fin: params[:dato_academico][:año_fin]).save
      antecedente_academico = AntecedenteAcademico.new(escuela_procedente_id: escuela.id, aspirante_id: @aspirante.id, fecha_inicio: nil, fecha_fin: nil, promedio: params[:dato_academico][:promedio], especialidad: params[:dato_academico][:especialidad], area_conocimiento_id: params[:dato_academico][:area_conocimiento_id], año_inicio: params[:dato_academico][:año_inicio], año_fin: params[:dato_academico][:año_fin]).save

      @aspirante.dato_personal.save

      render 'show'
    else
      render 'edit'
    end
  end
  #@aspirante=DatoPersonal.find_by_aspirante_id @aspirante.id
  def create
    begin
      Direccion.transaction do
        @aspirante = Aspirante.new(aspirante_params)
        @aspirante.usuario_id = current_usuario.id
        calle = params[:direccion][:calle]
        numero = params[:direccion][:numero]
        colonia = params[:direccion][:colonia]
        codigo_postal = params[:direccion][:codigo_postal]
        pais = Lugar.find(params[:direccion][:pais])
        if pais.nombre == 'MÉXICO'
          if params[:direccion][:localidad].nil?
            lugar=Lugar.find '300598'
          else
            lugar = Lugar.find(params[:direccion][:localidad])
          end
          @direccion = Direccion.create(calle: calle, numero: numero, colonia: colonia, codigo_postal: codigo_postal, lugar_id: lugar.id)
        else
          @direccion = Direccion.create(calle: calle, numero: numero, colonia: colonia, codigo_postal: codigo_postal, lugar_id: pais.id)
        end
        @aspirante.save
        dp = @aspirante.dato_personal.id
        dato_personal  = DatoPersonal.find(dp)
        dato_personal.direccion_id = @direccion.id
        lenguas = params[:datos_lenguas][:lengua_indigena]
        lenguas.each do |lenguas|
          DatoPersonalLenguaIndigena.new(dato_personal_id: dato_personal.id, lengua_indigena_id: lenguas).save
        end
        
        # se verifica si se copiaron los datos del domicilio del aspirante para el padre
        if params[:copiar_datos_hijoI] == "1"
          params[:familiar][:localidad_padre] = params[:direccion][:localidad]
        end
        padre = save_father(params[:familiar])
        AspiranteFamiliar.new(aspirante_id: @aspirante.id, familiar_id: padre.id).save

        # se verifica si se copiaron los datos del domicilio del aspirante para la madre
        if params[:copiar_datos_hijoII] == "1"
          params[:familiar][:localidad_madre] = params[:direccion][:localidad]
        end
        madre = save_mother(params[:familiar])
        AspiranteFamiliar.new(aspirante_id: @aspirante.id, familiar_id: madre.id).save

        if !params[:parentesco_tutor].nil?
          aux = params[:parentesco_tutor][:id]
          @tutor = save_tutor(params[:familiar],aux)
          AspiranteFamiliar.new(aspirante_id: @aspirante.id, familiar_id: @tutor.id).save
        end
        dato_medico = save_medical_data(params[:dato_medico])
        dato_personal.dato_medico_id = dato_medico.id
        dato_personal.save
        escuela = EscuelaProcedente.find_by_nombre(params[:dato_academico][:escuela_procedente_nombre])
        # antecedente_academico = AntecedenteAcademico.new(escuela_procedente_id: escuela.id, aspirante_id: @aspirante.id, fecha_inicio: params[:dato_academico][:fecha_inicio], fecha_fin: params[:dato_academico][:fecha_fin], promedio: params[:dato_academico][:promedio], especialidad: params[:dato_academico][:especialidad], area_conocimiento_id: params[:dato_academico][:area_conocimiento_id], año_inicio: params[:dato_academico][:año_inicio], año_fin: params[:dato_academico][:año_fin]).save
        antecedente_academico = AntecedenteAcademico.new(escuela_procedente_id: escuela.id, aspirante_id: @aspirante.id, fecha_inicio: nil, fecha_fin: nil, promedio: params[:dato_academico][:promedio], especialidad: params[:dato_academico][:especialidad], area_conocimiento_id: params[:dato_academico][:area_conocimiento_id], año_inicio: params[:dato_academico][:año_inicio], año_fin: params[:dato_academico][:año_fin]).save

app/views/aspirantes/_form_documento.html.erb
<div>
  <%= render 'mensaje_doc' %>
</div>
<div class="row">
  <div class="col-lg-12">
    <h4 class="text-center">Deberá ingresar la siguiente documentación</h4>
  </div>
</div>
<br>
<div class="row">
  <div class="col-lg-12">
    <div class="container">
      <%= form_for(@aspirante, url: save_documentos_aspirantes_path, html: { method: :post }) do |f| %>
          <div class="row">
            <div class="col-lg-9 col-sm-12">
              <% @documentos_fichas.each do |docs| %>
                  <tr>
                    <% if docs[:obligatorio]%>
                      <td>*</td>
                    <% else %>
                      <td></td>
                    <% end %>
                    <td>Selecciona el archivo de <%="#{docs[:nombre_documento]}"%></td>
                    <td id="tipo"> (jpeg,png,gif,pdf)</td>
                    <td>
                      <%= f.file_field "docs[#{docs[:id]}]", :accept => 'image/*, application/pdf', require: "#{docs[:obligatorio]}" %>
                    </td>
                  </tr>
                  <br>
              <% end %>

              <div class="col-lg-12">
              <h4>Ingresa la imagen de tu Fotografía</h4>
              </div>
              <tr>
                <td>*</td>
                <td>Selecciona el archivo de tu fotografía</td>
                <td id="tipo"> (jpeg,png,gif)</td>
                <td>
                  <%= f.file_field :foto, :accept => 'image/*', require: true %>
                </td>
              </tr>
              <br>
            <tr>
              <td colspan="2"><small>(*) Campos obligatorios</small></td>
            </tr>
            </div>

            <div class="col-lg-12">
              <div class="container">
                <%= link_to 'Cancelar', root_path, class: 'btn btn-primary btn-space pull-right' %>
                <%= f.submit 'Guardar Documentos', class: "btn btn-primary btn-space pull-right", data: { disable_with: "Por favor espere..." }, onclick: "javascript: return revisa_submit();" %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  function revisa_submit() {
      faltan = false;
      <% @documentos_fichas.each do |docs| %>
          <% if docs[:obligatorio] %>
              if (!faltan) {
                  var comprobante = document.getElementById("aspirante_docs[" + <%=docs[:id]%> +"]").value;
                  if (comprobante == "") {
                      faltan = true;
                  }
                  else {
                      if (/\.(jpe?g|png|gif|pdf)$/i.test(comprobante.toLowerCase())) {
                      }
                      else {
                          faltan = true;
                      }
                  }
              }
          <% end %>
      <% end %>
      var foto = document.getElementById("aspirante_foto").value;
      if (foto == "") {
          valido = false;
      }
      else {
          valido = (/\.(jpe?g|png|gif)$/i.test(foto.toLowerCase()));
      }
      if (valido !== true || faltan === true) {
          alert("Debes subir los documentos obligatorios, con extensión válida.");
      }
      ban = valido && !faltan
    return ban;
  }
</script>

app/views/aspirantes/_mensaje_doc.html.erb
<% unless @anuncio.blank? %>
  <% hora_actual = Time.now.strftime("%d-%m-%Y")  %>
  <% pos = 1  %>
  <%modulo = 5 %>

  <% @anuncio.each do  |anuncio |  %>

    <%if (hora_actual >= anuncio.desde && hora_actual <= anuncio.hasta && anuncio.modulo == modulo) %>

      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" class ="btn btn-light" data-dismiss="alert" >Enterado</button>
        <p>  <%= pos %>.- <%= anuncio.mensaje %> </p>
        <% pos+=1 %>
      </div>
    <% end  %>
  <% end %>
<% end %>

app/views/aspirantes/towns_options_edit.js.erb
var html = "<%= j(collection_select(:municipio, :id, @municipios, :id, :nombre, {prompt: '----- Municipios -----', selected: @municipio}, {class: 'form-control'})) %>";
$('#municipios').html(html);

if ($("#extranjero").is(':checked')) {
    $('select#municipio_id').css("display", "none");
    $("select#municipio_id").prop('required',false);
} else {
    $("select#municipio_id").attr("required", true);
    $("select#municipio_id").attr("disabled", true);
}

/* funcion que crea el select vacio de las localidades */
municipio = $("select#municipio_id :selected").val();
if (municipio == '') {
    var html = "<select class='form-control' id='localidad_id' required= 'required'> <option value=''>Seleccione un municipio para cargar las localidades</option></select>";
    $('#localidades').html(html);
    if ($("#extranjero").is(':checked')) {
        $('select#localidad_id').css("display", "none");
        $("select#localidad_id").prop('required', false);
    } else {
        $("select#localidad_id").attr("required", true);
    }
} else {
    municipio = $("select#municipio_id :selected").val();
    localidad = <%= @localidad %>
        $.ajax({
            url: "<%= localities_options_edit_aspirantes_path %>",
            type: "POST",
            data: {municipio_id: municipio, localidad_id: localidad}
        });
}


/* funcion que carga las localidades de acuerdo al municipio seleccionado */
$("select#municipio_id").on("change", function () {
    municipio = $("select#municipio_id :selected").val();
    $.ajax({
        url: "<%= localities_options_edit_aspirantes_path %>",
        type: "POST",
        data: {municipio_id: municipio}
    });
});

app/views/aspirantes/towns_options_father_edit.js.erb
var html = "<%= j(collection_select(:municipio_padre, :id, @municipios, :id, :nombre,{prompt: '----- Municipios -----', selected: @municipio}, {class: 'form-control'})) %>";
$('#municipios_padre').html(html);

if ($("#extranjero_padre").is(':checked')) {
    $('select#municipio_padre_id').css("display", "none");
    <!--    $("select#municipio_padre_id").prop('required',false);-->
} else {
    <!--    $("select#municipio_padre_id").attr("required", true);-->
    $("select#municipio_padre_id").attr("disabled", true);
}

/* funcion que crea el select vacio de las localidades */
municipio_padre = $("select#municipio_padre_id :selected").val();
if (municipio_padre == '') {
    var html = "<select class='form-control' id='localidad_padre_id'> <option value=''>Seleccione un municipio para cargar las localidades</option></select>";
    $('#localidades_padre').html(html);
    if ($("#extranjero_padre").is(':checked')) {
        $('select#localidad_padre_id').css("display", "none");
        $("select#localidad_padre_id").prop('required', false);
        <!--        $("select#localidad_padre_id").prop(d'required', false);-->
//        $("select#localidad_padre_id").attr("disabled", true);
    } else {
        <!--        $("select#localidad_padre_id").attr("required", true);-->
        $("select#localidad_padre_id").attr("disabled", true);
    }
} else {
    municipio_padre = $("select#municipio_padre_id :selected").val();
    localidad_padre= <%= @localidad %>
        $.ajax({
            url: "<%= localities_options_father_edit_aspirantes_path %>",
            type: "POST",
            data: {municipio_id: municipio_padre , localidad_id: localidad_padre}
        });
}


/* funcion que carga las localidades de acuerdo al municipio seleccionado */
$("select#municipio_padre_id").on("change", function () {
    municipio_padre = $("select#municipio_padre_id :selected").val();
    $.ajax({
        url: "<%= localities_options_father_edit_aspirantes_path %>",
        type: "POST",
        data: {municipio_id: municipio_padre}
    });
});

app/views/aspirantes/towns_options_mother.js.erb
var html = "<%= j(collection_select(:municipio_madre, :id, @municipios, :id, :nombre, {prompt: '----- Municipios -----', selected: @municipio}, {class: 'form-control'})) %>";
$('#municipios_madre').html(html);

if ($("#extranjero_madre").is(':checked')) {
    $('select#municipio_madre_id').css("display", "none");
    <!--    $("select#municipio_madre_id").prop('required',false);-->
} else {
    <!--    $("select#municipio_madre_id").attr("required", true);-->
}

/* funcion que crea el select vacio de las localidades */
municipio_madre = $("select#municipio_madre_id :selected").val();
if (municipio_madre == '') {
    var html = "<select class='form-control' id='localidad_madre_id'> <option value=''>Seleccione un municipio para cargar las localidades</option></select>";
    $('#localidades_madre').html(html);
    if ($("#extranjero_madre").is(':checked')) {
        $('select#localidad_madre_id').css("display", "none");
        <!--        $("select#localidad_madre_id").prop('required', false);-->
    } else {
        <!--        $("select#localidad_madre_id").attr("required", true);-->
    }
} else {
    municipio_madre = $("select#municipio_madre_id :selected").val();
    localidad_madre= <%= @localidad %>
        $.ajax({
            url: "<%= localities_options_mother_aspirantes_path %>",
            type: "POST",
            data: {municipio_id: municipio_madre , localidad_id: localidad_madre}
        });
}


/* funcion que carga las localidades de acuerdo al municipio seleccionado */
$("select#municipio_madre_id").on("change", function () {
    municipio_madre = $("select#municipio_madre_id :selected").val();
    $.ajax({
        url: "<%= localities_options_mother_aspirantes_path %>",
        type: "POST",
        data: {municipio_id: municipio_madre}
    });
});

app/views/aspirantes/update.js.erb
<%= render 'show' %>