config/routes.rb
Rails.application.routes.draw do
  resources :gestion_usuario do
    get :crear_cuentas, :on => :collection
    get :restablecer_cuentas, :on =>:collection
  end
   



  resources :solicitudes_fichas do
    post :readpdf, :on => :collection
    get :readpdf, :on => :collection
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  get 'anuncios/index'
  get "/anuncios", to: "anuncios#index"

  get "anuncios", to:"anuncios#index"
  get "anuncios/new", to: "anuncios#new"
  get "anuncios/:id", to:"anuncios#show"
  get "anuncios/:id/edit", to:"anuncios#edit"
  patch "/anuncios/:id", to:"anuncios#update", as: :anuncio
  post "anuncios", to:"anuncios#create"
  delete "/anuncios/:id", to:"anuncios#destroy"


  match 'solicitudes_fichas/aspi', :controller => 'solicitudes_fichas', :action => 'aspi', via: :get

  resources :solicitud_propedeutico do
    get :search_data_aspirantes_request, :on => :collection
    get :search_data_tipo_request, :on => :collection
    get :search_monto_request, :on => :collection
    get :search_concepto_request, :on => :collection
    post :guardar_sol, :on => :collection
  end

  resources :solicitudes_inscripciones do
    get :new_aspirante, :on => :collection
  end

  resources :solicitudes_reinscripciones

  resources :aspirantes do
    # get :show, :on => :collection
    post :towns_options, :on => :collection
    post :localities_options, :on => :collection

    post :towns_options_edit, :on => :collection
    post :localities_options_edit, :on => :collection

    post :towns_options_father, :on => :collection
    post :localities_options_father, :on => :collection
    post :towns_options_father_edit, :on => :collection
    post :localities_options_father_edit, :on => :collection


    post :towns_options_mother, :on => :collection
    post :localities_options_mother, :on => :collection

    post :towns_options_mother_edit, :on => :collection
    post :localities_options_mother_edit, :on => :collection


    post :towns_options_tutor, :on => :collection
    post :localities_options_tutor, :on => :collection

    post :towns_options_tutor_edit, :on => :collection
    post :localities_options_tutor_edit, :on => :collection

    get :autocomplete_origin_school, :on => :collection
    get :edit, :on => :collection
    get :new_documento, :on => :collection
    get :edit_documento, :on => :collection
    post :save_documentos, :on => :collection
    post :save_edit_documentos, :on => :collection
    get :registered_nss, :on => :collection
    get :registered_escuela, :on => :collection
  end
  resources :escolares

  resources :fichas do
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  devise_for :usuarios,controllers: { registrations: 'registrations' },  path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new_account', edit: 'edit/profile' }

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_user

  def index
    @dato_prope=""
    @anuncio = Anuncio.all
    @aspirante = Aspirante.find_by_curp(current_usuario.username.upcase)
    @aspirante_dato = Aspirante.where('upper(curp) = ?', current_usuario.username.upcase).first
    #Guarda los datos del aspirante que inicia sesión tanto de ficha, si existe, como de prope si existe
    unless(@aspirante_dato.blank?)
    @dato_ficha = Ficha.where('aspirante_id = ?', @aspirante_dato.id).first
    periodos_fichas = PeriodoPropedeutico.where("actual = ?", true).first
    unless periodos_fichas.blank?
    @dato_prope = InscripcionPropedeutico.joins(:solicitud_propedeutico=>:periodo_propedeutico).
        where("inscripciones_propedeuticos.aspirante_id = ? AND solicitudes_propedeuticos.periodo_propedeutico_id =?", @aspirante_dato.id,periodos_fichas.id).first
    end
    #Si los datos existen  guarda el estado que tengan, sino, lo deja como NINGUNO, para hacer la comparación de los
    # al momento de mostrar el menú
    if @dato_ficha.blank?
      @estado='NINGUNO'
    else
      @estado=@dato_ficha.estado
    end
    if @dato_prope.blank?
      @estadoprop='NINGUNO'
    else
      @estadoprop=@dato_prope.estado
    end
    end
    unless @aspirante.blank?
      aspirante = Aspirante.find(@aspirante.id)
      aspirante.update(:usuario_id => current_usuario.id)
      @documentos_fichas = DocumentoFicha.select(:id,:nombre_documento).all
      # Se agrega condición para validar si ya existe el registro del documento asociado al aspirante, ya no se cree un nuevo registro.
      # Se realiza una búsqueda por todos los documentos registrados para determinar cuál ya existe y omitir su registro.
      @documentos_fichas.each do |doc|
        aspirante_documento = AspiranteDocumento.where(aspirante_id: @aspirante.id, documento_ficha_id: doc.id)
        # Se cambia forma de realizar el if para crear el documento en caso de no existir
        if aspirante_documento.blank?
          @aspirante_documentos = AspiranteDocumento.find_or_create_by!(aspirante_id: @aspirante.id, documento_ficha_id: doc.id)
        end
      end
    end
  end

end

app/views/home/_mensajes.html.erb
<% unless @anuncio.blank? %>
<% hora_actual = Time.now.strftime("%d-%m-%Y")  %>
<% pos = 1  %>
  <%modulo = 1 %>

  <% @anuncio.each do  |anuncio |  %>
      <%if (hora_actual >= anuncio.desde && hora_actual <= anuncio.hasta && anuncio.modulo == modulo) %>

      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" class ="btn btn-light" data-dismiss="alert" >Enterado</button>
        <p>  <%= pos %>.- <%= anuncio.mensaje %> </p>
        <% pos+=1 %>
      </div>
      <% end  %>
  <% end %>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <div class="my-logo">
      <div class="pull-left">
        <a class="hamburger">
          <i class="sr-only">Toggle navigation</i>
          <i class="fa fa-bars" aria-hidden="true"></i>
        </a>
      </div>

      <div class="col-xs-8 col-xs-offset-2">
        <%= image_tag('logo_Nes.png', class: 'user-image logo center-block size-img') %>
      </div>

      <div class="pull-right">
        <a class="navbar-toggle collapsed btnbarra" data-toggle="collapse" data-target="#barra-menu">
          <i class="sr-only">Toggle navigation</i>
          <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
        </a>
      </div>
    </div>

    <div class="my-div-right">
      <div class="navbar-collapse  collapse" id="barra-menu">
        <ul class="nav navbar-nav my-right-ul">
        <%if current_usuario.rol != 'ADMINISTRADOR' %>
 
          <li>
            <%= link_to edit_usuario_registration_path, class: 'mytool icons', 'data-toggle': 'tooltip', 'data-placement': 'bottom', 'data-original-title': 'Usuario' do %>
              <%= fa_icon 'user' %>
            <% end %>
          </li>
        <%end%>
          <li>
            <%= link_to destroy_usuario_session_path, class: "mytool icons", 'data-toggle': 'tooltip', 'data-placement': "bottom", 'data-original-title': 'Salir', method: :delete do %>
              <%= fa_icon "sign-out" %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/_sidebar.html.erb
<div id="wrapper" class="">
  <!-- Sidebar -->
  <div class="navbar navbar-fixed-top" id="sidebar-wrapper" role="navigation">
    <ul class="nav sidebar-nav">
      <li class="my-li-nav">
        <%= link_to 'Inicio', root_path %>
      </li>
      <% if current_usuario.rol =='ADMINISTRADOR'%>
        <li class="my-li-nav">
          <%= link_to 'Cambiar contraseña de administrador',edit_usuario_registration_path %>
        </li>
        <li class="my-li-nav">
          <%= link_to 'Gestionar usuarios', gestion_usuario_index_path %>
        </li>
        <li class="my-li-nav">
          <%= link_to 'Crear usuarios', crear_cuentas_gestion_usuario_index_path, data: {:confirm => "Este proceso puede demorar un tiempo por favor espere hasta ver el mensaje de confirmacion.\n\n¿Estás seguro de crear usuarios de tipo alumno a partir de alumnos?"} %>
        </li>
        <li class="my-li-nav">
          <%= link_to 'Reiniciar cuentas de usuario',restablecer_cuentas_gestion_usuario_index_path, data: {:confirm => "Este proceso puede demorar un tiempo por favor espere hasta ver el mensaje de confirmacion.\n\n¿Estás seguro de restablecer todas las cuentas de usuario de tipo alumno?"} %>
        </li>
        <li class="my-li-nav">
          <%= link_to 'Gestionar anuncios',anuncios_index_path %>
        </li>
      <% else %>
        <% alumno = Alumno.where("(tipo ='ALUMNO' or tipo='BAJA_TEM' or tipo='BAJA_TEMP' ) and curp=?",current_usuario.username.upcase).first %>
        <% aspirante = Aspirante.where('upper(curp) = ?', current_usuario.username.upcase).first %>
        <% unless alumno.blank? %>
          <% if alumno.tiene_inscripcion? %>
              <li class="my-li-nav">
                <%= link_to 'Solicitud de Reinscripción', solicitudes_reinscripciones_path, data: {:confirm => "Aqui va el reglamento, proporcionar dicha informacion."} %>
              </li>
          <% else %>
            <% if !aspirante.blank? and aspirante.tiene_prope? %>
              <li>
                <%= link_to 'Solicitud de Inscripcion', solicitudes_inscripciones_path, data: {:confirm => "Aqui va el reglamento, proporcionar dicha informacion."} %>
              </li>
            <% end %>
          <% end %>
        <% else %>
          <% if PeriodoFicha.is_period_of_application_for_tokens? %>
            <% if current_usuario.aspirante.nil? && alumno.blank?%>
              <li class="my-li-nav">
                <%= link_to 'Solicitud de Ficha', new_aspirante_path , onclick: "javascript: return revisa_submit();"%>
              </li>
            <% else %>
              <% if !(aspirante.tiene_prope_q? == 'ACEPTADO' || aspirante.tiene_prope_q? == 'ACEPTADO CONDICIONADO')%>
                <% if aspirante.is_aspirante_with_request? == Aspirante::NUEVO_DOCUMENTO %>
                  <li class="my-li-nav">
                    <%= link_to 'Solicitud de Ficha', new_documento_aspirantes_path %>
                  </li>
                <% else %>
                  <li class="my-li-nav">
                    <%= link_to 'Solicitud de Ficha', solicitudes_fichas_path %>
                  </li>
                <% end %>
              <% end %>
            <% end %>
            <% if !aspirante.blank? %>
              <% if aspirante.tiene_ficha? %>
                <li class="my-li-nav">
                  <%= link_to 'Consulta de Ficha', fichas_path %>
                </li>
              <% end %>
            <% end %>
          <% end %>
          <% if current_usuario.aspirante && alumno.blank? %>
            <li class="my-li-nav">
                <%= link_to 'Datos del aspirante', edit_aspirante_path(current_usuario.aspirante.id) %>
            </li>
          <% end %>
          <% unless aspirante.blank? %>
            <% if PeriodoPropedeutico.is_period_of_application_for_tokens? %>
                <% if current_usuario.aspirante.nil? %>
                  <li class="my-li-nav">
                    <%= link_to 'Solicitud de Propedéutico', new_aspirante_path %>
                  </li>
                <% else %>
                  <li class="my-li-nav">
                    <%= link_to 'Solicitud de Propedéutico', new_solicitud_propedeutico_path %>
                  </li>
                  <li class="my-li-nav">
                    <%= link_to 'Consulta de propedéutico', solicitud_propedeutico_index_path %>
                  </li>
                <% end %>
            <% end %>
            <% if Fecha.is_inscripcion_period_active? &&  (aspirante.tiene_prope_q? == 'ACEPTADO' || aspirante.tiene_prope_q? == 'ACEPTADO CONDICIONADO')%>
              <li class="my-li-nav">
                <%= link_to 'Solicitud de Inscripción', new_solicitud_inscripcion_path, data: {:confirm => "Aqui va el reglamento, proporcionar dicha informacion."} %>
              </li>
            <% end  %>
          <% end %>
        <% end %>
      <% end %>
      <li class="my-li-nav">
        <%= link_to 'Ayuda', root_path %>
      </li>
    </ul>
  </div>
</div>
<script type="text/javascript">
    function revisa_submit(){
        alert( "Se te recomienda tener listos los documentos (en formato jpeg, gif, png, pdf) que se te solicitarán antes de finalizar tu solicitud, los documentos son: \n" +
            "1. Comprobante de pago\n" +
            "2. Copia del acta de nacimiento\n" +
            "3. Copia del certificado de secundaria\n" +
            "4. Copia del certificado de bachillerato o constancia de estudios\n" +
            "5. Copia de CURP\n" +
            "6. Fotografía tipo infantil preferentemente blanco y negro");
    }
</script>

app/views/home/index.html.erb
<div class="container">
  <div>
    <%= render 'home/mensajes' %>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2 col-xs-12">
      <h2 class="text-center"> <b>¡Bienvenido al Portal de Inscripciones!</b></h2>
      <br>
<!--      <h2><%#=  @anuncie.mensaje %></h2>-->
      <br>
    </div>
    <div class="col-md-4 col-md-offset-4 col-sm-8 col-sm-offset-2 col-xs-12">
      <%= image_tag(('Logo-UTM1.png'), :class => "img-responsive center-block logo-utm") %>
    </div>
  </div>
</div>