config/routes.rb
Rails.application.routes.draw do
  resources :gestion_usuario do
    get :crear_cuentas, :on => :collection
    get :restablecer_cuentas, :on =>:collection
  end
   



  resources :solicitudes_fichas do
    post :readpdf, :on => :collection
    get :readpdf, :on => :collection
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  get 'anuncios/index'
  get "/anuncios", to: "anuncios#index"

  get "anuncios", to:"anuncios#index"
  get "anuncios/new", to: "anuncios#new"
  get "anuncios/:id", to:"anuncios#show"
  get "anuncios/:id/edit", to:"anuncios#edit"
  patch "/anuncios/:id", to:"anuncios#update", as: :anuncio
  post "anuncios", to:"anuncios#create"
  delete "/anuncios/:id", to:"anuncios#destroy"


  match 'solicitudes_fichas/aspi', :controller => 'solicitudes_fichas', :action => 'aspi', via: :get

  resources :solicitud_propedeutico do
    get :search_data_aspirantes_request, :on => :collection
    get :search_data_tipo_request, :on => :collection
    get :search_monto_request, :on => :collection
    get :search_concepto_request, :on => :collection
    post :guardar_sol, :on => :collection
  end

  resources :solicitudes_inscripciones do
    get :new_aspirante, :on => :collection
  end

  resources :solicitudes_reinscripciones

  resources :aspirantes do
    # get :show, :on => :collection
    post :towns_options, :on => :collection
    post :localities_options, :on => :collection

    post :towns_options_edit, :on => :collection
    post :localities_options_edit, :on => :collection

    post :towns_options_father, :on => :collection
    post :localities_options_father, :on => :collection
    post :towns_options_father_edit, :on => :collection
    post :localities_options_father_edit, :on => :collection


    post :towns_options_mother, :on => :collection
    post :localities_options_mother, :on => :collection

    post :towns_options_mother_edit, :on => :collection
    post :localities_options_mother_edit, :on => :collection


    post :towns_options_tutor, :on => :collection
    post :localities_options_tutor, :on => :collection

    post :towns_options_tutor_edit, :on => :collection
    post :localities_options_tutor_edit, :on => :collection

    get :autocomplete_origin_school, :on => :collection
    get :edit, :on => :collection
    get :new_documento, :on => :collection
    get :edit_documento, :on => :collection
    post :save_documentos, :on => :collection
    post :save_edit_documentos, :on => :collection
    get :registered_nss, :on => :collection
    get :registered_escuela, :on => :collection
  end
  resources :escolares

  resources :fichas do
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  devise_for :usuarios,controllers: { registrations: 'registrations' },  path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new_account', edit: 'edit/profile' }

  root 'home#index'
end

app/models/ficha.rb
class Ficha < ActiveRecord::Base
  belongs_to :aspirante
  belongs_to :solicitud_ficha
  belongs_to :carrera
  belongs_to :ciclo

  ENTREGADA = 'ENTREGADA'
  ENVIADO = 'ENVIADO'
  TERMINADO = 'TERMINADO'
  CANCELADO = 'CANCELADO'

  VENTANILLA = 'VENTANILLA'
  ONLINE = 'EN LINEA'

  def self.get_number_available(periodo)
    numero_nes = Token.where("ciclo_id = ?", periodo).order("CAST(numero as integer) desc").limit(1)
    if numero_nes.blank?
      numero_nes = 0
    else
      numero_nes = numero_nes.first.numero.to_i
    end

    numero_inscripciones = Ficha.where("ciclo_id = ?", periodo).order("CAST(numero as integer) desc").limit(1)
    if numero_inscripciones.blank?
      numero_inscripciones = 0
    else
      numero_inscripciones = numero_inscripciones.first.numero.to_i
    end

    maximo = 1
    if numero_nes > numero_inscripciones
      maximo = numero_nes.to_i + 1
    else
      maximo = numero_inscripciones.to_i + 1
    end

    '%04d' % (maximo)
  end
end

app/controllers/fichas_controller.rb
class FichasController < ApplicationController
  before_action :require_user

  require 'piet'

  include SendDoc

  def index
    @anuncio = Anuncio.all
    ciclo = Ciclo.get_actual
    periodos_fichas = PeriodoFicha.where("actual = ?", true).first
    unless current_usuario.aspirante.blank?
      @fichas = SolicitudFicha.joins(:ficha).where("solicitudes_fichas.aspirante_id = ? AND solicitudes_fichas.ciclo_id = ? ", current_usuario.aspirante.id, periodos_fichas.ciclo_id)
      # @solicitud_ficha = SolicitudFicha.where("solicitudes_fichas.aspirante_id = ? AND solicitudes_fichas.ciclo_id = ? ", current_usuario.aspirante.id, periodos_fichas.ciclo_id).order("created_at desc").first
      @faltan_documentos = faltan_documentos_obligatorios(current_usuario.aspirante.id, periodos_fichas.ciclo_id)
    else
      @fichas = []
    end

  end

  def new
  end
  def aspi
    @periodo = params[:ciclo_id]
    usuario = current_usuario
    #Se identifica el periodo que esta como actual pero de fichas, no del sistema nes
    ciclo_periodo = PeriodoFicha.find_by_actual(true)
    current_ciclo = Ciclo.find_by_actual(true)
    ciclo = Ciclo.find_by_inicio_and_fin_and_tipo(current_ciclo.inicio, current_ciclo.fin, 'A')
    #solicitud = SolicitudFicha.find_by_aspirante_id(usuario.aspirante.id)
    # Se toma la solicitud hecha en ese periodo seleccionado
    unless ciclo_periodo.blank?
      solicitud = SolicitudFicha.where("aspirante_id = ? AND ciclo_id = ?", usuario.aspirante.id, ciclo_periodo.ciclo_id).last
    end

    # puts"aca" +usuario.aspirante.id.to_s
    if usuario
      @universidad = solicitud.sede_ficha.sede
      @periodo= I18n.l(solicitud.sede_ficha.fecha_examen,:format => "%d de %B del %Y")
      @hora=solicitud.sede_ficha.hora_examen
    end
    @datos = []
    @encabezado = []
    contador = 0
    if !ciclo.blank?
      #Al igual que arriba se busca la información pero tomando en cuenta el periodo de fichas actual no el del sistema NES
      unless ciclo_periodo.blank?
        solicitud = SolicitudFicha.where("aspirante_id = ? AND ciclo_id = ?", usuario.aspirante.id, ciclo_periodo.ciclo_id).last
        @solicitudes_fichas = Ficha.where("aspirante_id = ? AND ciclo_id = ?", usuario.aspirante.id, ciclo_periodo.ciclo_id).first
      end
      #ficha = Ficha.find_by_solicitud_ficha_id(params[:id].to_i)
      # ficha = Ficha.find_by_id(params[:id].to_i)

      campus = Campus.first
      universidad = Universidad.first
      contenido_comprobante_ficha = ContenidoComprobanteFichas.first
      if !solicitud.blank?  && SolicitudFicha::ONLINE
        carrera = Carrera.find_by_id(@solicitudes_fichas.carrera_id) unless @solicitudes_fichas.blank?
        @datos << { :id => usuario.aspirante.id,
                    :nombre=>    usuario.aspirante.nombre.upcase.to_s,
                    :ap_pat=>   usuario.aspirante.apellido_paterno.upcase.to_s,
                    :ap_mat=>    usuario.aspirante.apellido_materno.upcase.to_s,
                    :carrera=> ( carrera.blank? ? "---" : carrera.nombre_carrera.to_s),
                    :no_ficha=> (@solicitudes_fichas.blank? or @solicitudes_fichas.numero.blank?) ? "" : @solicitudes_fichas.numero,
                    :lema => (universidad.lema unless (universidad.blank? or universidad.lema.blank?)),
                    :ciudad => (campus.ciudad.to_s unless (campus.blank? or campus.ciudad.blank?)),
                    :avisos_en => (contenido_comprobante_ficha.avisos_en.to_s unless contenido_comprobante_ficha.blank?),
                    :texto_guias => (contenido_comprobante_ficha.texto_guias.to_s unless contenido_comprobante_ficha.blank?),
                    :muestramensaje =>(faltan_documentos_opcionales(usuario.aspirante.id)),
                    :proceso => (@solicitudes_fichas.solicitud_ficha.proceso == "EN LINEA") ? "TRÁMITE REALIZADO EN LÍNEA".to_s : "TRÁMITE REALIZADO EN VENTANILLA".to_s

        }
        name = usuario.aspirante.nombre_archivo
        if !name.blank?
          _path = SolicitudFicha::RUTA_COMPROBANTES
          fpath = File.join(_path,name)
          if(File.exists?(fpath))
            @fotoaspi = Base64.encode64(File.open(fpath, "rb").read)
          end
        end

        @muestramensaje = (faltan_documentos_opcionales(usuario.aspirante.id))
      end
      @encabezado = {
          :universidad => solicitud.sede_ficha.sede,

      }

    end
    template = render_to_string('solicitudes_fichas/aspi.xml.builder',layout: false)
    xpath = '/reporte/informacion/datos'
    send_doc(template, xpath, "FichaExamenSeleccion", "FichaExamenSeleccion",'pdf')

  end
  def faltan_documentos_obligatorios(aspirante_id, ciclo)
    solicitud_ficha = SolicitudFicha.where("solicitudes_fichas.aspirante_id = ? AND solicitudes_fichas.ciclo_id = ? ", aspirante_id, ciclo).order("created_at desc").first
    if !solicitud_ficha.blank?
      asp_docs_rechazados = AspiranteDocumento.where( :aspirante_id => aspirante_id, :aceptado => 'FALSE')
      asp_docs = AspiranteDocumento.where(:aspirante_id => aspirante_id)
      docs_obligatorios = DocumentoFicha.all #where(:obligatorio => true)
      aspirante = Aspirante.find(aspirante_id)

      if asp_docs_rechazados.blank? and asp_docs.size > 0 and (solicitud_ficha.comprobante_aceptado == true) and (aspirante.fotografia_aceptado == true)
        return true
      end

      if (solicitud_ficha.comprobante_aceptado == false)
        return false
      end

      if (aspirante.fotografia_aceptado == false)
        return false
      end

      docs_obligatorios.each do |doc|
        if !asp_docs_rechazados.select {|d| d.documento_ficha_id == doc.id}.blank?
          return false
        end
      end
    end
    return true
  end
  def faltan_documentos_opcionales(aspirante_id)
    asp_docs_rechazados = AspiranteDocumento.where( :aspirante_id => aspirante_id, :aceptado => 'FALSE')
    asp_docs = AspiranteDocumento.where(:aspirante_id => aspirante_id)
    docs_opcionales = DocumentoFicha.where(:obligatorio => false)

    if asp_docs_rechazados.blank? and asp_docs.size >= 0
      return false
    end
    docs_opcionales.each do |doc|
      if !asp_docs_rechazados.select {|d| d.documento_ficha_id == doc.id}.blank?
        return true
      end
    end
    return false
  end
end

app/views/fichas/_mensajes.html.erb
<% unless @anuncio.blank? %>
  <% hora_actual = Time.now.strftime("%d-%m-%Y")  %>
  <% pos = 1  %>
  <%modulo = 6 %>

  <% @anuncio.each do  |anuncio |  %>

    <%if (hora_actual >= anuncio.desde && hora_actual <= anuncio.hasta && anuncio.modulo == modulo) %>

      <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" class ="btn btn-light" data-dismiss="alert" >Enterado</button>
        <p>  <%= pos %>.- <%= anuncio.mensaje %> </p>
        <% pos+=1 %>
      </div>
    <% end  %>
  <% end %>
<% end %>

app/views/fichas/index.html.erb
<div>
  <%= render 'mensajes' %>
</div>
<h2 class="text-center"><b>Fichas</b></h2>
<div class="container">
  <% id = 0 %>
  <% unless @fichas.blank? %>
    <% @fichas.each do |ficha| %>
      <div class="well espaciado">
        <div class="row espaciado">
          <div class="col-lg-2 col-sm-3 col-xs-12">
            <span class="circle center-block">
              <%= id += 1 %>
            </span>
          </div>
          <div class="col-lg-6 col-sm-4 col-xs-12">
            <h3 class="center-block">Datos de la Ficha</h3>
          </div>
        </div>
        <div class="row espaciado">
          <div class="col-lg-12">
            <div class="table-responsive">
              <table class="table table-bordered table-striped">
                <thead>
                  <th class="text-center">Estado de la Ficha</th>
                  <th class="text-center">Número Ficha</th>
                  <th class="text-center">Carrera</th>
                  <th class="text-center">Tipo Curso</th>
                </thead>
                <tbody>

                  <tr>
                    <td>
                      <% if ficha.ficha.estado == "TERMINADO" or ficha.ficha.estado == "PENDIENTE" %>
                        <span class="label label-warning"><%= ficha.ficha.estado %></span>
                      <% end %>
                      <% if ficha.ficha.estado == "CANCELADO" or ficha.ficha.estado == "NO ACEPTADO" %>
                        <span class="label label-danger"><%= ficha.ficha.estado %></span>
                      <% end %>
                      <% if ficha.ficha.estado == "ACEPTADO CONDICIONADO" or ficha.ficha.estado == "ACEPTADO" %>
                        <span class="label label-success"><%= ficha.ficha.estado %></span>
                      <% end %>
                      <% if ficha.ficha.estado == "ASIGNADO" %>
                        <span class="label label-info"><%= ficha.ficha.estado %></span>
                        <div id="contenedor_botones_inferiores" align="center">
                          <%= link_to "Ficha para examen de selección PDF", aspi_fichas_path(:id => ficha.aspirante.id), :target=>'_blank' %>
                          <%= fa_icon "download" %>
                        </div>
                      <% end %>
                    </td>
                    <td class="text-center"><%= ficha.ficha.numero %></td>
                    <td class="text-center"><%= ficha.ficha.carrera.nombre_carrera %></td>
                    <td class="text-center"><%= ficha.sede_ficha.periodo_ficha.tipo %></td>
                  </tr>
                  <tr>
                    <th class="text-right">Aspirante</th>
                    <td colspan="4"><%= current_usuario.aspirante.full_name %></td>
                  </tr>
                </tbody>
              </table>
            </div>

          </div>
        </div>
      </div>
    <% end %>
   <div id="contenedor_botones_inferiores" align="center">
      <%= link_to "Salir", destroy_usuario_session_path, :fa_icon =>'sign-out',:class=>'tn btn-danger',method: :delete%>
      <%= fa_icon "sign-out" %>
    </div>
  <% else %>
    <div class="row">
      <div class="col-lg-12">
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <thead>
              <th class="text-center">Estado de la Ficha</th>
              <th class="text-center">Carrera</th>
              <th class="text-center">Curso Propedéutico</th>
            </thead>
            <tbody>
              <tr>
                <td colspan="3" class="text-center">Sin fichas entregadas.</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
  <div class="table-responsive">
    <table class="table table-bordered table-striped">
      <thead>
      </thead>
      <tbody>
      <% if !@faltan_documentos.nil? and !@faltan_documentos%>
          <tr>
            <td colspan="3" class="text-center">Favor de revisar tu documentación. <%= link_to 'Documentos', edit_documento_aspirantes_path %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>