config/routes.rb
Rails.application.routes.draw do
  resources :gestion_usuario do
    get :crear_cuentas, :on => :collection
    get :restablecer_cuentas, :on =>:collection
  end
   



  resources :solicitudes_fichas do
    post :readpdf, :on => :collection
    get :readpdf, :on => :collection
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  get 'anuncios/index'
  get "/anuncios", to: "anuncios#index"

  get "anuncios", to:"anuncios#index"
  get "anuncios/new", to: "anuncios#new"
  get "anuncios/:id", to:"anuncios#show"
  get "anuncios/:id/edit", to:"anuncios#edit"
  patch "/anuncios/:id", to:"anuncios#update", as: :anuncio
  post "anuncios", to:"anuncios#create"
  delete "/anuncios/:id", to:"anuncios#destroy"


  match 'solicitudes_fichas/aspi', :controller => 'solicitudes_fichas', :action => 'aspi', via: :get

  resources :solicitud_propedeutico do
    get :search_data_aspirantes_request, :on => :collection
    get :search_data_tipo_request, :on => :collection
    get :search_monto_request, :on => :collection
    get :search_concepto_request, :on => :collection
    post :guardar_sol, :on => :collection
  end

  resources :solicitudes_inscripciones do
    get :new_aspirante, :on => :collection
  end

  resources :solicitudes_reinscripciones

  resources :aspirantes do
    # get :show, :on => :collection
    post :towns_options, :on => :collection
    post :localities_options, :on => :collection

    post :towns_options_edit, :on => :collection
    post :localities_options_edit, :on => :collection

    post :towns_options_father, :on => :collection
    post :localities_options_father, :on => :collection
    post :towns_options_father_edit, :on => :collection
    post :localities_options_father_edit, :on => :collection


    post :towns_options_mother, :on => :collection
    post :localities_options_mother, :on => :collection

    post :towns_options_mother_edit, :on => :collection
    post :localities_options_mother_edit, :on => :collection


    post :towns_options_tutor, :on => :collection
    post :localities_options_tutor, :on => :collection

    post :towns_options_tutor_edit, :on => :collection
    post :localities_options_tutor_edit, :on => :collection

    get :autocomplete_origin_school, :on => :collection
    get :edit, :on => :collection
    get :new_documento, :on => :collection
    get :edit_documento, :on => :collection
    post :save_documentos, :on => :collection
    post :save_edit_documentos, :on => :collection
    get :registered_nss, :on => :collection
    get :registered_escuela, :on => :collection
  end
  resources :escolares

  resources :fichas do
    post :aspi, :on => :collection
    get :aspi, :on => :collection
  end

  devise_for :usuarios,controllers: { registrations: 'registrations' },  path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'new_account', edit: 'edit/profile' }

  root 'home#index'
end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  MODULO = [
    {id: 1, nombre:'Home'},
    {id: 2, nombre:'Solicitud de ficha'},
    {id: 3, nombre:'Nuevo Aspirante'},
    {id: 4, nombre:'Consulta de ficha'},
    {id: 5, nombre:'Documentos'},
    {id: 6, nombre:'Fichas'},
    {id: 7, nombre:'Consulta de propedeútico'},
    {id: 8, nombre:'Solicitud de inscripción'},
    {id: 9, nombre:'Solicitud de reinscripción'}
  ]
  #Se crea un arreglo de opciones para mostrar los mensajes en el lugar seleccionado
  validates :mensaje, presence: true, length:{maximum: 200}
  validates :desde, presence: true
  validates :hasta, presence: true
  validates :modulo, presence: true

  #Método para mostrar el lugar que se haya seleccionado para el mensaje
  def self.get_lugar_anuncio(id)
    lugar = 'NINGUNO'
    MODULO.each do |mod|
      if mod[:id] == id
        lugar = mod[:nombre]
      end
    end
    lugar
  end

  #el partial _mensajes, muestra los mensajes que haya para el lugar al que ingresaron, y que tenga seleccionado el módulo
end

app/controllers/anuncios_controller.rb
class AnunciosController < ApplicationController
  before_action :require_user , :allow_access

  before_action :find_anuncio, only: [:show, :edit, :destroy,:update]

  add_flash_types :notice

  #Lista todos los registros de mensajes de la base de datos

  def index
    @anuncio=Anuncio.all
  end

  #Muestra la información de un registro

  def show
  end

  def edit
  end

  def update
    @anuncio.update(mensaje: params[:anuncio][:mensaje],desde: params[:anuncio][:desde], hasta: params[:anuncio][:hasta], modulo: params[:anuncio][:modulo])
    redirect_to action: :index
    flash[:notice] = "El mensaje ha sido actualizado correctamente"
  end

  #Crea el mensaje

  def new
    @anuncio = Anuncio.new
  end

  def create
    @anuncio = Anuncio.create(mensaje: params[:anuncio][:mensaje],desde: params[:anuncio][:desde], hasta: params[:anuncio][:hasta], modulo: params[:anuncio][:modulo])

    if @anuncio.save
      redirect_to action: :index
      flash[:notice] = "El mensaje ha sido creado correctamente"
    else
      render :new
    end
  end



  def destroy
    @anuncio.destroy
    redirect_to action: :index
    if @anuncio.destroy
      flash[:notice] = "El mensaje fue eliminado correctamente"
    else
      flash[:alert] = "El mensaje no se puede eliminar"
    end
  end

  def find_anuncio
    @anuncio = Anuncio.find(params[:id])
  end

end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/views/anuncios/_form.html.erb
<%= form_for (@anuncio) do |f| %>

     <% @anuncio.errors.full_messages.each do |message| %>
    <div class="alert alert-danger">
       *<%= message %>
    </div>
     <%end%>

    <div class="form-group">
      <span class="input-group-addon", width="100%"> <strong>Mensaje</strong> </span>
      <%= f.text_area :mensaje, placeholder:"Escribe el mensaje", class:"form-control",style:"width:100%;" %>
    </div>

    <div class="input-group" id="fecha">
      <span class="input-group-addon"><strong>Fecha desde</strong> </span>
        <%= date_field :anuncio, :desde, class: 'form-control', placeholder: 'Ingrese la Fecha en que inicia el mensaje.', min: DateTime.now.strftime("%d-%m-%Y") %>
        <span class="input-group-addon"><strong>Fecha hasta</strong></span>
        <%= date_field :anuncio, :hasta, class: 'form-control', placeholder: 'Ingrese la Fecha en que termina el mensaje.', min: DateTime.now.strftime("%d-%m-%Y") %>
        <span class="input-group-addon"><strong>Módulo</strong></span>
        <%= select :anuncio , :modulo, Anuncio::MODULO.collect {|p| [p[:nombre], p[:id]]}, {prompt: '---Seleccione el modulo---'}, class: 'form-control', required: true %>
    </div>


          <%= f.submit "Agregar", :class =>"btn btn-info"%>
          <%= link_to 'Regresar', anuncios_index_path, :class => 'btn btn-danger' %>
<%end%>

app/views/anuncios/_row.html.erb
<tr>
  <td><%= anuncio.mensaje %></td>
  <td><%= anuncio.desde.strftime("%d de %B del 20%y") %></td>
  <td><%= anuncio.hasta.strftime("%d de %B del 20%y") %></td>

  <td style="text-align: center">
    <i class='fa fa-eye fa-lg'></i>
    <i class='fa fa-edit fa-lg'></i>
  </td>
</tr>

app/views/anuncios/_tabla.html.erb
<table class="table table-bordered table-hover">
  <thead>
  <tr>
    <th style= "width:50%">Mensaje</th>
    <th style= "width:15%">Desde</th>
    <th style= "width:15%">Hasta</th>
    <th style= "text-align: center" style= "width:20%">Opciones</th>
    <th style= "width:15%">Lugar</th>
  </tr>
  </thead>
  <tbody>
  <% unless @anuncio.blank? %>
    <% @anuncio.each do |anuncio|  %>

        <tr>
          <td><%= anuncio.mensaje %></td>
          <td><%=anuncio.desde.strftime("%d de %B del 20%y") %></td>
          <td><%=anuncio.hasta.strftime("%d de %B del 20%y") %></td>
          <td style="text-align: center">
            <%= link_to '', href: "#{anuncio.id}/edit", class: 'btn btn-icono', 'data-toggle': 'tooltip', 'data-placement': 'bottom', 'data-original-title': 'Editar' do %>
              <i class="fa fa-edit fa-lg"></i>
            <% end %>
            <%= link_to '', href: "#{anuncio.id}",method: :delete, class: 'btn btn-icono', 'data-toggle': 'tooltip',data: {confirm: "¿Estás seguro que deseas eliminar el mensaje?"}, 'data-placement': 'bottom', 'data-original-title': 'Editar' do %>
              <i class="fa fa-trash fa-lg"></i>
            <% end %>
          </td>
          <td><span class="label label-info"> <%= @anuncio.get_lugar_anuncio(anuncio.modulo) %></span>

          </td>

            <% end %>

            <% else %>
            <tr>
              <td colspan="5" style="text-align: center">NO EXISTEN MENSAJES</td>
            </tr>
            <% end %>
  </tbody>
</table>

app/views/anuncios/edit.html.erb
<div class="table-wrapper  table-responsive">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-12 col-xs-12">
        <h2>EDITAR MENSAJE</h2>
      </div>
    </div>
  </div>
  <div>
    <div class="tab-content">
      <div class="tab-pane active" id="pet">
        <div class="container-fluid">
          <div class="panel-body">
            <div class="row">
              <div class="row">
                <div id="div-tabla" class="table-responsive">
                  <%= render "anuncios/form" %>
                </div>
              </div>
              <br>
            </div>

            <br>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/anuncios/index.html.erb
<div class="table-wrapper  table-responsive">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-12 col-xs-12">
        <h2>MENSAJES</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <%= link_to 'Agregar', anuncios_new_path, :class => 'btn btn-primary pull-right float-right'%>
  </div>
  <div>
  <div class="tab-content">
    <div class="tab-pane active" id="pet">
      <div class="container-fluid">
        <div class="panel-body">
          <div class="row">
            <div class="row">
                <div id="div-tabla" class="table-responsive">
                  <%= render 'anuncios/tabla' %>
                </div>
            </div>
            <br>
          </div>

          <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/anuncios/new.html.erb
<div class="table-wrapper  table-responsive">
  <div class="table-title">
    <div class="row">
      <div class="col-sm-12 col-xs-12">
        <h2>AGREGAR NUEVO MENSAJE</h2>
      </div>
    </div>
  </div>
  <div>
    <div class="tab-content">
      <div class="tab-pane active" id="pet">
        <div class="container-fluid">
          <div class="panel-body">
            <div class="row">
              <div class="row">
                <div id="div-tabla" class="table-responsive">
                  <%= render "anuncios/form" %>
                </div>
              </div>
              <br>
            </div>

            <br>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/anuncios/show.html.erb
<h1><%= @anuncio.mensaje %></h1>
<div>
  <%= @anuncio.desde %>
  <%= @anuncio.hasta %>
</div>
<div>
  <%= link_to "Eliminar el articulo", @anuncio, method: :delete%>
</div>